repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.6.1
    hooks:
      - id: ruff
        args: [--fix]
  - repo: local
    hooks:
      - id: update-papers-badge
        name: Update papers badge & README summary
        entry: python scripts/update_papers_badge.py
        language: system
        pass_filenames: false
